"""HTML report generation for analysis results."""

from __future__ import annotations

import html
import json
from datetime import datetime
from pathlib import Path
from typing import Any

import numpy as np

from feaweld.pipeline.workflow import WorkflowResult


REPORT_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>feaweld Analysis Report - {{ title }}</title>
    <style>
        body { font-family: 'Segoe UI', Arial, sans-serif; margin: 40px; color: #333; }
        h1 { color: #1a5276; border-bottom: 2px solid #2980b9; padding-bottom: 10px; }
        h2 { color: #2471a3; margin-top: 30px; }
        table { border-collapse: collapse; width: 100%; margin: 15px 0; }
        th, td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; }
        th { background-color: #2980b9; color: white; }
        tr:nth-child(even) { background-color: #f2f2f2; }
        .pass { color: #27ae60; font-weight: bold; }
        .fail { color: #e74c3c; font-weight: bold; }
        .warning { color: #f39c12; font-weight: bold; }
        .summary-box { background: #eaf2f8; padding: 15px; border-radius: 5px; margin: 15px 0; }
        .error-box { background: #fadbd8; padding: 15px; border-radius: 5px; margin: 15px 0; }
        .section { margin: 20px 0; }
        img { max-width: 100%; margin: 10px 0; }
        .figure-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 15px; margin: 15px 0; }
        .figure-item { text-align: center; }
        .figure-item img { border: 1px solid #ddd; border-radius: 4px; }
        .figure-caption { font-style: italic; color: #555; margin-top: 5px; font-size: 0.9em; }
        .figure-full { margin: 15px 0; text-align: center; }
        footer { margin-top: 40px; color: #888; font-size: 0.9em; border-top: 1px solid #ddd; padding-top: 10px; }
    </style>
</head>
<body>
    <h1>feaweld Analysis Report</h1>
    {{ content }}
    <footer>
        Generated by feaweld v{{ version }} on {{ timestamp }}
    </footer>
</body>
</html>"""


def generate_report(result: WorkflowResult, output_dir: str | Path | None = None) -> str:
    """Generate an HTML report from workflow results.

    Args:
        result: WorkflowResult from run_analysis
        output_dir: Directory to write report file (default: result.case.output_dir)

    Returns:
        Path to generated HTML report.
    """
    from feaweld import __version__

    out_dir = Path(output_dir or result.case.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    content_parts = []

    # Case info
    content_parts.append(_section_case_info(result))

    # Mesh info
    if result.mesh is not None:
        content_parts.append(_section_mesh_info(result))

    # FEA results summary
    if result.fea_results is not None:
        content_parts.append(_section_fea_results(result))

    # Post-processing results
    if result.postprocess_results:
        content_parts.append(_section_postprocess(result))

    # Fatigue results
    if result.fatigue_results:
        content_parts.append(_section_fatigue(result))

    # Probabilistic results
    if result.probabilistic_results:
        content_parts.append(_section_probabilistic(result))

    # Visualization figures (gracefully skipped if matplotlib not installed)
    try:
        from feaweld.visualization.report_figures import generate_report_figures
        figures = generate_report_figures(result)
        if figures:
            content_parts.append(_section_figures(figures))
    except ImportError:
        pass  # matplotlib not available — skip figures
    except Exception:
        pass  # other errors — don't break report generation

    # Errors
    if result.errors:
        content_parts.append(_section_errors(result))

    content = "\n".join(content_parts)

    report_html = REPORT_TEMPLATE.replace("{{ title }}", html.escape(result.case.name))
    report_html = report_html.replace("{{ content }}", content)
    report_html = report_html.replace("{{ version }}", __version__)
    report_html = report_html.replace("{{ timestamp }}", datetime.now().isoformat())

    report_path = out_dir / f"{result.case.name}_report.html"
    report_path.write_text(report_html)

    result.report_path = str(report_path)
    return str(report_path)


def _section_case_info(result: WorkflowResult) -> str:
    case = result.case
    return f"""
    <div class="section">
        <h2>Analysis Case</h2>
        <div class="summary-box">
            <strong>Name:</strong> {html.escape(case.name)}<br>
            <strong>Description:</strong> {html.escape(case.description or "N/A")}<br>
            <strong>Joint Type:</strong> {case.geometry.joint_type.value}<br>
            <strong>Material:</strong> {html.escape(case.material.base_metal)} (base), {html.escape(case.material.weld_metal)} (weld)<br>
            <strong>Solver:</strong> {case.solver.solver_type.value} ({case.solver.backend})<br>
            <strong>Status:</strong> <span class="{'pass' if result.success else 'fail'}">{'PASS' if result.success else 'ERRORS'}</span>
        </div>
    </div>
    """


def _section_mesh_info(result: WorkflowResult) -> str:
    mesh = result.mesh
    return f"""
    <div class="section">
        <h2>Mesh Summary</h2>
        <table>
            <tr><th>Property</th><th>Value</th></tr>
            <tr><td>Number of Nodes</td><td>{mesh.n_nodes:,}</td></tr>
            <tr><td>Number of Elements</td><td>{mesh.n_elements:,}</td></tr>
            <tr><td>Element Type</td><td>{mesh.element_type.value}</td></tr>
            <tr><td>Dimensions</td><td>{mesh.ndim}D</td></tr>
            <tr><td>Physical Groups</td><td>{', '.join(mesh.physical_groups.keys()) or 'None'}</td></tr>
        </table>
    </div>
    """


def _section_fea_results(result: WorkflowResult) -> str:
    fea = result.fea_results
    rows = ""

    if fea.stress is not None:
        vm = fea.stress.von_mises
        rows += f"""
        <tr><td>Max von Mises Stress</td><td>{np.max(vm):.2f} MPa</td></tr>
        <tr><td>Min von Mises Stress</td><td>{np.min(vm):.2f} MPa</td></tr>
        <tr><td>Mean von Mises Stress</td><td>{np.mean(vm):.2f} MPa</td></tr>
        """

    if fea.displacement is not None:
        max_disp = np.max(np.linalg.norm(fea.displacement, axis=1))
        rows += f'<tr><td>Max Displacement</td><td>{max_disp:.4f} mm</td></tr>'

    if fea.temperature is not None:
        if fea.temperature.ndim == 1:
            rows += f"""
            <tr><td>Max Temperature</td><td>{np.max(fea.temperature):.1f} C</td></tr>
            <tr><td>Min Temperature</td><td>{np.min(fea.temperature):.1f} C</td></tr>
            """

    return f"""
    <div class="section">
        <h2>FEA Results</h2>
        <table>
            <tr><th>Quantity</th><th>Value</th></tr>
            <tr><td>Analysis Type</td><td>{'Transient' if fea.is_transient else 'Static'}</td></tr>
            {rows}
        </table>
    </div>
    """


def _section_postprocess(result: WorkflowResult) -> str:
    rows = ""
    for method, pp in result.postprocess_results.items():
        if isinstance(pp, dict):
            for key, value in pp.items():
                if isinstance(value, (int, float)):
                    rows += f'<tr><td>{html.escape(method)}</td><td>{html.escape(key)}</td><td>{value:.4f}</td></tr>'

    return f"""
    <div class="section">
        <h2>Post-Processing Results</h2>
        <table>
            <tr><th>Method</th><th>Parameter</th><th>Value</th></tr>
            {rows}
        </table>
    </div>
    """


def _section_fatigue(result: WorkflowResult) -> str:
    rows = ""
    for key, value in result.fatigue_results.items():
        if isinstance(value, dict):
            for k2, v2 in value.items():
                if isinstance(v2, (int, float)):
                    rows += f'<tr><td>{html.escape(key)}</td><td>{html.escape(k2)}</td><td>{v2:.2f}</td></tr>'
        elif isinstance(value, (str, int, float)):
            rows += f'<tr><td colspan="2">{html.escape(key)}</td><td>{html.escape(str(value))}</td></tr>'

    return f"""
    <div class="section">
        <h2>Fatigue Assessment</h2>
        <table>
            <tr><th>Method</th><th>Parameter</th><th>Value</th></tr>
            {rows}
        </table>
    </div>
    """


def _section_probabilistic(result: WorkflowResult) -> str:
    prob = result.probabilistic_results
    rows = ""
    for key, value in prob.items():
        if isinstance(value, (int, float)):
            rows += f'<tr><td>{html.escape(key)}</td><td>{value:.4f}</td></tr>'

    return f"""
    <div class="section">
        <h2>Probabilistic Analysis</h2>
        <table>
            <tr><th>Statistic</th><th>Value</th></tr>
            {rows}
        </table>
    </div>
    """


def _section_figures(figures: dict[str, str]) -> str:
    """Build HTML section with embedded base64 PNG figures."""
    from feaweld.visualization.report_figures import html_img_tag

    _CAPTIONS = {
        "stress_distribution": "Von Mises Stress Distribution",
        "sn_curve": "S-N Fatigue Curve",
        "dong_decomposition": "Dong Structural Stress Decomposition",
        "hotspot_extrapolation": "Hot-Spot Stress Extrapolation",
        "weld_group": "Weld Group Geometry",
        "engineering_dashboard": "Engineering Assessment Dashboard",
    }

    # Dashboard gets full width if present
    dashboard_html = ""
    if "engineering_dashboard" in figures:
        cap = _CAPTIONS.get("engineering_dashboard", "Dashboard")
        img = html_img_tag(figures["engineering_dashboard"], alt=cap)
        dashboard_html = f'<div class="figure-full">{img}<div class="figure-caption">{cap}</div></div>'

    # Other figures in 2-column grid
    grid_items = ""
    for key, b64 in figures.items():
        if key == "engineering_dashboard":
            continue
        cap = _CAPTIONS.get(key, key.replace("_", " ").title())
        img = html_img_tag(b64, alt=cap)
        grid_items += f'<div class="figure-item">{img}<div class="figure-caption">{cap}</div></div>\n'

    grid_html = ""
    if grid_items:
        grid_html = f'<div class="figure-grid">{grid_items}</div>'

    return f"""
    <div class="section">
        <h2>Visualizations</h2>
        {dashboard_html}
        {grid_html}
    </div>
    """


def _section_errors(result: WorkflowResult) -> str:
    errors = "".join(
        f"<li>{html.escape(e)}</li>" for e in result.errors
    )
    return f"""
    <div class="error-box">
        <h2>Errors</h2>
        <ul>{errors}</ul>
    </div>
    """
